//
//  DeveloperPreview.swift
//  AirBnb
//
//  Created by Olzhas Suleimenov on 06.03.2024.
//

import Foundation

class DeveloperPreview {
    var listings: [Listing] = [
        .init(id: NSUUID().uuidString,
              ownerUid: NSUUID().uuidString,
              ownerName: "John Smith",
              ownerImageUrl: "male-profile-photo",
              numberofBedrooms: 4,
              numberOfBathrooms: 3,
              numberOfGuests: 4,
              numberOfBeds: 4,
              pricePerNight: 567,
              latitude: 25.7850,
              longitude: -80.1936,
              imageURLs: ["hotel1", "hotel2", "hotel3", "hotel4"],
              address: "124 Main St",
              city: "Miami",
              state: "Florida",
              title: "Miami Villa",
              rating: 4.86,
              features: [.selfCheckIn, .superHost],
              amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "John Smith",
                  ownerImageUrl: "male-profile-photo",
                  numberofBedrooms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  imageURLs: ["hotel1", "hotel2", "hotel3", "hotel4"],
                  address: "124 Main St",
                  city: "Miami",
                  state: "Florida",
                  title: "Miami Villa",
                  rating: 4.86,
                  features: [.selfCheckIn, .superHost],
                  amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "John Smith",
                  ownerImageUrl: "male-profile-photo",
                  numberofBedrooms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  imageURLs: ["hotel1", "hotel2", "hotel3", "hotel4"],
                  address: "124 Main St",
                  city: "Miami",
                  state: "Florida",
                  title: "Miami Villa",
                  rating: 4.86,
                  features: [.selfCheckIn, .superHost],
                  amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "John Smith",
                  ownerImageUrl: "male-profile-photo",
                  numberofBedrooms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  imageURLs: ["hotel1", "hotel2", "hotel3", "hotel4"],
                  address: "124 Main St",
                  city: "Miami",
                  state: "Florida",
                  title: "Miami Villa",
                  rating: 4.86,
                  features: [.selfCheckIn, .superHost],
                  amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa),
        
            .init(id: NSUUID().uuidString,
                  ownerUid: NSUUID().uuidString,
                  ownerName: "John Smith",
                  ownerImageUrl: "male-profile-photo",
                  numberofBedrooms: 4,
                  numberOfBathrooms: 3,
                  numberOfGuests: 4,
                  numberOfBeds: 4,
                  pricePerNight: 567,
                  latitude: 25.7850,
                  longitude: -80.1936,
                  imageURLs: ["hotel1", "hotel2", "hotel3", "hotel4"],
                  address: "124 Main St",
                  city: "Miami",
                  state: "Florida",
                  title: "Miami Villa",
                  rating: 4.86,
                  features: [.selfCheckIn, .superHost],
                  amenities: [.wifi, .alarmSystem, .balcony, .laundry, .tv], type: .villa)
    ]
}
